package com.lovenote.app.auth

import android.content.Context
import androidx.credentials.ClearCredentialStateRequest
import androidx.credentials.CredentialManager
import androidx.credentials.GetCredentialRequest
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.FirebaseAuthRecentLoginRequiredException
import com.google.firebase.auth.FirebaseUser
import com.google.firebase.auth.GoogleAuthProvider
import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.firestore.SetOptions
import kotlinx.coroutines.tasks.await

class AuthRepository(
    private val auth: FirebaseAuth = FirebaseAuth.getInstance(),
    private val db: FirebaseFirestore = FirebaseFirestore.getInstance(),
) {
    val currentUser: FirebaseUser? get() = auth.currentUser

    suspend fun signInWithGoogle(activityContext: Context): FirebaseUser {
        val option = GetGoogleIdOption.Builder()
            .setFilterByAuthorizedAccounts(false)
            .setServerClientId(webClientId(activityContext))
            .build()
        val request = GetCredentialRequest.Builder()
            .addCredentialOption(option)
            .build()
        val response = CredentialManager.create(activityContext)
            .getCredential(activityContext, request)
        val idToken = GoogleIdTokenCredential.createFrom(response.credential.data).idToken
        val user = auth.signInWithCredential(GoogleAuthProvider.getCredential(idToken, null))
            .await().user ?: error("Sign-in returned no user")
        db.collection("users").document(user.uid).set(
            mapOf(
                "displayName" to (user.displayName ?: ""),
                "photoUrl" to (user.photoUrl?.toString() ?: ""),
            ),
            SetOptions.merge(),
        ).await()
        return user
    }

    /**
     * Permanently deletes the account: all shared couple data (messages,
     * notes, answers, events), the pairing, the user profile, local caches,
     * and finally the Firebase sign-in itself.
     */
    suspend fun deleteAccount(activityContext: Context) {
        val user = auth.currentUser ?: return
        val uid = user.uid

        val coupleId = db.collection("users").document(uid)
            .get().await().getString("coupleId")
        if (coupleId != null) {
            val coupleRef = db.collection("couples").document(coupleId)
            for (sub in listOf("messages", "notes", "daily", "events", "state")) {
                while (true) {
                    val page = coupleRef.collection(sub).limit(200).get().await()
                    if (page.isEmpty) break
                    val batch = db.batch()
                    page.documents.forEach { batch.delete(it.reference) }
                    batch.commit().await()
                }
            }
            coupleRef.delete().await()
        }
        db.collection("users").document(uid).delete().await()

        try {
            user.delete().await()
        } catch (_: FirebaseAuthRecentLoginRequiredException) {
            // Firebase requires a fresh sign-in before account deletion.
            reauthenticate(activityContext, user)
            user.delete().await()
        }

        // Local traces: cached widget note, notification bookkeeping, credentials.
        activityContext.getSharedPreferences("note_widget_cache", Context.MODE_PRIVATE)
            .edit().clear().apply()
        activityContext.getSharedPreferences("notify_state", Context.MODE_PRIVATE)
            .edit().clear().apply()
        runCatching {
            CredentialManager.create(activityContext)
                .clearCredentialState(ClearCredentialStateRequest())
        }
    }

    private suspend fun reauthenticate(activityContext: Context, user: FirebaseUser) {
        val option = GetGoogleIdOption.Builder()
            .setFilterByAuthorizedAccounts(true)
            .setServerClientId(webClientId(activityContext))
            .build()
        val request = GetCredentialRequest.Builder()
            .addCredentialOption(option)
            .build()
        val response = CredentialManager.create(activityContext)
            .getCredential(activityContext, request)
        val idToken = GoogleIdTokenCredential.createFrom(response.credential.data).idToken
        user.reauthenticate(GoogleAuthProvider.getCredential(idToken, null)).await()
    }

    // default_web_client_id is generated by the google-services plugin; resolve it
    // at runtime so the app compiles before google-services.json exists.
    private fun webClientId(context: Context): String {
        val resId = context.resources.getIdentifier(
            "default_web_client_id", "string", context.packageName,
        )
        require(resId != 0) { "Firebase is not configured yet (google-services.json missing)" }
        return context.getString(resId)
    }
}
