package com.lovenote.app.auth

import android.content.Context
import androidx.credentials.CredentialManager
import androidx.credentials.GetCredentialRequest
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.FirebaseUser
import com.google.firebase.auth.GoogleAuthProvider
import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.firestore.SetOptions
import kotlinx.coroutines.tasks.await

class AuthRepository(
    private val auth: FirebaseAuth = FirebaseAuth.getInstance(),
    private val db: FirebaseFirestore = FirebaseFirestore.getInstance(),
) {
    val currentUser: FirebaseUser? get() = auth.currentUser

    suspend fun signInWithGoogle(activityContext: Context): FirebaseUser {
        val option = GetGoogleIdOption.Builder()
            .setFilterByAuthorizedAccounts(false)
            .setServerClientId(webClientId(activityContext))
            .build()
        val request = GetCredentialRequest.Builder()
            .addCredentialOption(option)
            .build()
        val response = CredentialManager.create(activityContext)
            .getCredential(activityContext, request)
        val idToken = GoogleIdTokenCredential.createFrom(response.credential.data).idToken
        val user = auth.signInWithCredential(GoogleAuthProvider.getCredential(idToken, null))
            .await().user ?: error("Sign-in returned no user")
        db.collection("users").document(user.uid).set(
            mapOf(
                "displayName" to (user.displayName ?: ""),
                "photoUrl" to (user.photoUrl?.toString() ?: ""),
            ),
            SetOptions.merge(),
        ).await()
        return user
    }

    // default_web_client_id is generated by the google-services plugin; resolve it
    // at runtime so the app compiles before google-services.json exists.
    private fun webClientId(context: Context): String {
        val resId = context.resources.getIdentifier(
            "default_web_client_id", "string", context.packageName,
        )
        require(resId != 0) { "Firebase is not configured yet (google-services.json missing)" }
        return context.getString(resId)
    }
}
